"""
Django settings for my_e2e_project project.

Generated by 'django-admin startproject' using Django 3.0.14.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import urllib
import django_heroku


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '8j=1od&^z9bp7)n=@zjve42w(p$08c_gt%intna&^s$*^w*4wr'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'personal_app.apps.PersonalAppConfig',
    'corsheaders',
    'rest_framework.authtoken',
    'rest_auth',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'rest_auth.registration',
    'mongo_auth',
]

# Minimal settings (all mandatory)
MANGO_JWT_SETTINGS = {
    "db_host": "cluster0.3hdcb.mongodb.net", # Use srv host if connecting with MongoDB Atlas Cluster
    "authSource":'admin',
    "db_name": "e2e_db",
    "db_user": "test",
    "db_pass": "12345"
}

# # Or use Advanced Settings (including optional settings)
# MANGO_JWT_SETTINGS = {
#     "db_host": "cluster0.3hdcb.mongodb.net",
#     "db_name": "e2e_db",
#     "db_user": "test",
#     "db_pass": "12345",
#     "auth_collection": "user_profile", #"personal_users", # default is "user_profile"
#     "fields": ("email", "password","firstname","lastname","phone","type","country","region"), # default
#     "jwt_secret": "secret", # default
#     "jwt_life": 7, # default (in days)
#     # "secondary_username_field": "mobile" # default is None
# }

###for jean####
# Or use Advanced Settings (including optional settings)
MANGO_JWT_SETTINGS = {
    "db_host": "cluster0.3hdcb.mongodb.net",
    "db_name": "e2e_db",
    "db_user": "test",
    "db_pass": "12345",
    "auth_collection": "jean_countdown", #"personal_users", # default is "user_profile"
    "fields": ("vimeo_id", "vimeo_link","created_at","text_msg","date"), # default
    "jwt_secret": "secret", # default
    "jwt_life": 7, # default (in days)
    # "secondary_username_field": "mobile" # default is None
}

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
]

# REST_AUTH_SERIALIZERS = {
#     'LOGIN_SERIALIZER': '../personal_app/LoginSerializer',
#     'TOKEN_SERIALIZER': '../personal_app/TokenSerializer',
#     'PASSWORD_RESET_SERIALIZER':'../personal_app/TokenSerializer',
#     'PASSWORD_RESET_CONFIRM_SERIALIZER':'../personal_app/passwordResetSerializer',
#     'USER_DETAILS_SERIALIZER':'../personal_app/UserDetailsSerializer',
#     'REGISTER_SERIALIZER':'../personal_app/RegisterSerializer'
# }

ROOT_URLCONF = 'my_e2e_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'my_e2e_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        'NAME': 'e2e_db',
    }
}

REST_FRAMEWORK = {'DEFAULT_PERMISSION_CLASSES': ['rest_framework.permissions.AllowAny'],
                  # 'DEFAULT_AUTHENTICATION_CLASSES': [
                  #     'rest_framework.authentication.BasicAuthentication',
                  #     'rest_framework.authentication.SessionAuthentication',
                  # ]
                  }

CORS_ORIGIN_ALLOW_ALL = True

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
django_heroku.settings(locals())